- src/Button/Button.js
- src/Button/Button.mdx
- src/theme.js
> ### Summary
Adds the ability for button groups to layout their children in a vertical column at predefined or custom breakpoints.
**Example usage:**
```jsx
<Button.Group vertical="768" />
<Button.Group vertical={576} />
<Button.Group vertical /> //=> defaults to "sm" (768px)
<Button.Group vertical="lg" /> //=> any predefined breakpoint in `theme.grid.sizes`
```
> Add vertical stacking to button group

- src/Form/Input.js
Necessary for getting `styled-components` to pass down class names to underlying components.
> Pass className prop to Input component's children

- package-lock.json
- package.json
- src/Form/Formbot.js
discovered via sappira-inc/web-app#116
> fix(Formbot): Update minLength and maxLength error messages

- src/Form/Checkbox.js
- src/Form/Checkbox.mdx
- src/Form/Radio.mdx
- src/Form/RadioGroup.js
looks like this was the issue here: https://app.asana.com/0/821652619613450/929543341861746/f
`componentDidUpdate` gets called after `handleChange` on user input - this was calling `handleChange` again with the old value (because `this.props.value` isn't updated until `Formbot.setState` is called and propagated back down)
> fix(RadioGroup): don't loop state updates

- src/Linkify/Linkify.js
- src/Linkify/Linkify.mdx
- src/Linkify/Linkify.spec.js
- src/Linkify/__snapshots__/Linkify.spec.js.snap
> ### Summary
Fixed an issue with the `Linkify` component allowing execution of arbitrary HTML/JS that could be used for XSS attacks. 
Props to @kylealwyn for the actual implementation.
> Don't use dangerous HTML in Linkify

- src/Button/Button.js
- src/Button/Button.mdx
> ### Summary 
Fixed issue with buttons having both `outline` and `loading` props displaying a transparent spinner.
> Fix spinner color for outline buttons

- src/Form/Input.js
- src/Form/Input.mdx
> fix(Input): Use parentNode.removeChild to teardown textarea shadow node in support of older browsers

- src/Form/Formbot.js
- src/Form/Input.mdx
The previous logic would invalidate the field, losing the scope of the synthetic onChange event handler in the valdiation promise. After validation, Formbot would then set the new values, causing Input cursor to jump to the end.
> fix(Formbot): Set field value before validating in onChange handler

- src/Dropdown/Dropdown.js
The [redesigned EMR dashboard](https://app.asana.com/0/821652619613450/1104820821162262/f) requires the following properties of the dropdown component to be configurable: border-radius, border, offset.
Related CMS PR: https://github.com/sappira-inc/cms/pull/225
Tested locally via `yarn docs`
> fix(Dropdown): Support for configuring dropdown offset

- src/Form/Input.js
fixes warning when supplying a ref setter function
```
Warning: Failed prop type: Invalid prop `forwardedRef` of type `function` supplied to `Input`, expected `object`.
in Input
in Unknown (created by EasyInput)
in EasyInput (created by ForwardRef)
```
> fix(Input): allow forwardedRef to be a function

- src/Form/Checkbox.js
- src/Form/Radio.mdx
- src/Form/RadioGroup.js
These changes fix a bug where `<RadioGroup/>` accepted a `size` (string) prop, but it's child component `<Checkbox/>` only accepted `iconSize` (number), and `fontSize` (number). Also styles are now passed down to support more customization (margins, etc.), such as required by [EMR Message Conversation List](https://app.asana.com/0/821652619613450/1108680987294666/f).
> (fix)RadioGroup: Size prop mismatch, configure style

- src/Card/Card.js
This change wraps `<Card/>` in `React.forwardRef`.
https://app.asana.com/0/887402852146010/1112252089781752/f
> fix(Card): Wrap in React.forwardRef

- src/Dropdown/Dropdown.js
- src/Dropdown/Dropdown.mdx
- src/Dropdown/__snapshots__/Dropdown.spec.js.snap
These changes allow the `<Dropdown/>` component's `<TriggerWrapper/>`(`styled(Dropdown.Trigger)`) to be styled so that it may, for example, fill the available width of its parent container.
> (fix)Dropdown: Configure <Dropdown.Trigger/> style

- src/Card/Card.js
- src/Icon/Icon.js
- src/Icon/Icon.spec.js
- src/Icon/__snapshots__/Icon.spec.js.snap
- src/utils.js
When the `Icon` component was being provided with a `className` prop, this prop was overwriting the default class name generated for the icon, namely `mdi mdi-X`. In the web-app several icons disappeared mysteriously and this was because those component had this structure...
```js
<Icon className="blah" name="message" />
```
...which is explained by this snippet:
```js
<Icon className="bagels" name="message" /> //=> render Icon with className prop
const Icon = createComponent({
props: () => ({
className: 'mdi mdi-message', //=> generated by `Icon.getClassName`
});
// and then inside of `utils#createComponent`
const resolvedProps = {
...baseProps(props), //=> className: mdi mdi-message
...props, //=> className: overwritten by bagels!!!   
};
```
> fix(Icon): Prevent passed className from being overwritten

- package-lock.json
- package.json
- src/Form/DateInput.js
- src/Form/DateInput.spec.js
- src/Form/EasyInput.js
- src/Form/Formbot.example.js
- src/Form/Input.js
- src/Form/Input.mdx
- src/Form/PhoneInput.js
- src/Form/PhoneInput.spec.js
- src/Form/Select.js
- src/Form/__snapshots__/DateInput.spec.js.snap
- src/Form/__snapshots__/PhoneInput.spec.js.snap
- src/utils.js
- Adds new `<PhoneInput />` and `<DateInput />` components for easy input masking
- Fixes some existing styling issues with `<Select />`
> feat(Form): Add <PhoneInput /> and <DateInput />; Clean up <Select />

- src/Linkify/Linkify.js
- src/Linkify/Linkify.mdx
- src/Linkify/Linkify.spec.js
- src/Linkify/__snapshots__/Linkify.spec.js.snap
@choochootrain @cehsu manipulating the source string beyond carriage return conversion seems too brittle to me. If we choose to only use a source string prop, we also drop our dependency on `renderStaticToMarkup`
> Linkify proposal

- src/Linkify/Linkify.js
- src/Linkify/Linkify.mdx
- src/Linkify/Linkify.spec.js
- src/Linkify/__snapshots__/Linkify.spec.js.snap
These changes allow the `<Linkify/>` component to display text formatted as a code block (according to [gfm](https://github.github.com/gfm/)) as normal text.
> fix(Linkify): Skip code block formatting

- src/Form/PhoneInput.js
Not sure where/how the value is being set to null, so adding this defensive cast until we can dig more
https://sentry.io/organizations/heydoctor/issues/996939211/?environment=beta&project=290802&query=is%3Aunresolved
> fix(PhoneInput): Cast null to empty string

- src/Modal/Modal.dropdownExample.js
- src/Modal/Modal.example.js
- src/Modal/Modal.js
- src/Modal/Modal.mdx
These changes:
- Lock focus in modals (via `react-focus-lock`)
- Adds an example with a dropdown (to illustrate how returnFocus is handled)
Next steps:
- add VRT with puppeteer, and tie into CI
- consider using [react-focus-on](https://github.com/theKashey/react-focus-on) for modals as recommended by [react-focus-lock](https://github.com/theKashey/react-focus-lock#more)
- close on escape keypress
> fix(Modal): Lock focus

- src/Dropdown/Dropdown.js
Gatsby breaks when building:
```
11:24:58 AM:   2842 |   transitionDuration: PropTypes.number,
11:24:58 AM:   2843 |   transitionTimingFunction: PropTypes.string,
11:24:58 AM: > 2844 |   portalNode: PropTypes.instanceOf(Element)
11:24:58 AM:        |                        ^
11:24:58 AM:   2845 | };
11:24:58 AM:   2846 | Dropdown.defaultProps = {
11:24:58 AM:   2847 |   placement: 'bottom-start',
11:24:58 AM: 
11:24:58 AM:   WebpackError: ReferenceError: Element is not defined
```
> fix(Dropdown): Fix SSR by removing direct reference to Element in prop types

- package.json
- src/Form/Checkbox.js
- src/Form/CheckboxGroup.js
- src/__snapshots__/utils.spec.js.snap
- src/utils.js
- src/utils.spec.js
- Add the ability to pass `colorOn ` & `colorOff` when using a `CheckboxGroup`
- Add the ability to extend theme based styling into variants as well
- Changes are based on issues encountered with PRD updates
**Problem**
When extending the styles for a particular component at the theme level, I can't dig deeper into a per variant basis. This causes problems when trying to change the `hover` state for a secondary button only for example.
**Solution**
Allow for the ability to pass styles into the variant level as well. 
For example if I want to target a secondary button only I can pass this following in `theme.js`. The `style` key accepts a template string or a style object.
```
{  
Button: {
variants: {
secondary: {
style: `
&:hover {
background-color: tomato;
}
`,
},
},
},
}
```
> feat: Checkbox color updates & Extending theme based styling to variants

- src/Dropdown/Dropdown.js
- src/Dropdown/Dropdown.spec.js
- src/Dropdown/__snapshots__/Dropdown.spec.js.snap
This sets the default width as auto (150 is too arbitrary) and adds general support for string widths, such as 1rem.
To account for dynamically sized dropdowns
https://app.asana.com/0/1131771498685767/1132620207943367
> feat(Dropdown): Add support for string widths

- src/Form/Formbot.js
> Bug scenario:
1. Blur out of a required field, e.g zip
2. Use `Formbot#setValues` to update the field programmatically
3. We expect the validation message to disappear but it doesn't 
The issue was twofold: 
1. We weren't running validations as a callback after values were set with `#setValues`
2. `#updateField` in `#validateAllFields` wasn't being called with`{ validated: false }`, which caused `#validateField` to bail when it reached this condition: 
```js
const fieldState = this.state.fields[field] || {};
// field was already validated the first time around and
// thus bailed out of subsequent validations
if (fieldState.validated) { validations
resolve();
return;
}
```
> fix(Formbot): Validate fields when setting state directly

- src/Form/Input.js
- src/Form/Label.js
This change ensures that floating labels appear for zero values.
1. Blur out of an input with a floating label, and a value of 0 (can be tested via `value={0}`).
3. We expect the label to remain, but it doesn't: 
1. Zero values were not being accounted for in checking whether to display floating labels. Checking for zero values allows the label to be displayed:
> fix(Input): Display floating input label if value is not undefined

- src/Modal/Modal.mdx
Netlify build failing to do incorrectly capitalized file name. Non issue on Macs. First time using Github editor for PR ... not bad
> chore(Modal): Use correct file name casing for linux build

- doczrc.js
Deploy preview now working as intended.
The index.html script paths were prefixed by the base set in the config, e.g. `/molekule/static/js/bitcoinminer.js`. Docs on Netlify will be hosted at the root so base is no longer needed. I'm doing this from an iPad on a train, forgive me.
> chore(docs): Remove base path for distro build

- src/Form/EasyInput.js
- src/Form/FormError.js
- src/Form/Formbot.example.js
- src/Form/Formbot.js
- src/Form/Formbot.mdx
Our validation schema library `yup` allows for sync as well as async validations and we've not been able to utilize this feature due to the constraint of `Formbot` validating forms synchronously. Most recently, Scott on the `web-app` and myself on the `mobile-app` have run into an issue where we needed to hit an API endpoint as part of validating a patient's address (zip + state matching) but making this work required some ninjitsu (utilizing local state, effects to run the validations, etc). With this proposal, all of that goes away and we can define smarter validation schemas that support async validations. 
There are no breaking changes in the PR so we can adopt as needed, but we now allow the ability to pass a function to `validationSchema`. The function will be called with one …
> Async Formbot Validations

- src/Form/Formbot.js
- src/Form/Formbot.mdx
It was discovered when refactoring the `AddressForm` component that the `onChange` notification in `FormBot` was called before field updating/validation was complete.  This is an issue if in an `onChange` handler for `FormBot` you are expecting to test for form validity (i.e. updating your UI according to the validity of a recent change to form data).  Additionally the `return` from the async validation block was triggering the `finally` handler causing premature promise resolution and triggering the `onChange` handler before validations were complete.
> fix(validations): Fix handling of async validations as well as order of onChange notification

- src/Form/Formbot.js
Using a function as a state updater seems to fix an issue with stale state data preventing a validation function from running.
> fix: Use updater function in setState for Formbot updates

- src/Form/FormError.js
`<FormError />` can be used outside Formbot context and thus we need to ensure that we safely look up the error in case the context is `null`.
> fix(FormError): Fix crash in case context is null

- docs/theme.mdx
- src/Badge/__snapshots__/Badge.spec.js.snap
- src/Card/Card.js
- src/Card/__snapshots__/Card.spec.js.snap
- src/Dropdown/Dropdown.js
- src/Dropdown/__snapshots__/Dropdown.spec.js.snap
- src/Form/Checkbox.js
- src/Form/CheckboxGroup.js
- src/Form/Input.js
- src/Form/Select.js
- src/Form/Switch.js
- src/Form/__snapshots__/DateInput.spec.js.snap
- src/Form/__snapshots__/PhoneInput.spec.js.snap
- src/Modal/Modal.dropdownExample.js
- src/Modal/Modal.example.js
- src/Modal/Modal.js
- src/Tabs/Tabs.js
- src/Tabs/__snapshots__/Tabs.spec.js.snap
- src/theme.js
There are a lot of existing PRs that rely on the colors being updated. Instead of making those changes on every PR, I made this to update colors in one sweep.
Colors were changed for specific components because `gray =>  grey` as well as basic theme file changes. If any components match the Figma file (as far as colors go), it is purely coincidence. Those specific changes will be made in their respective PRs.
Colors like `green` and `blue` were kept to mitigate breaking changes. Coincidentally, our primary and secondary colors are blue/green so it's only natural to make those the blue and green for our color scheme. But I wanted to leave those colors in to make this work out of the box.
> feat(Colors): Updates colors

- src/Alert/Alert.js
- src/Badge/Badge.js
- src/Badge/__snapshots__/Badge.spec.js.snap
- src/Button/Button.js
- src/Button/Button.mdx
- src/Dropdown/__snapshots__/Dropdown.spec.js.snap
- src/theme.js
The logic to determine Button styles felt slightly cumbersome. Rather than trying to be too tricky on how to handle different button styles, e.g. outlines, text only, colors, I propose we configure every variation as a variant, with naming conventions such as `colorText` or `colorOutline`. The `variant` blocks in the theme are now fully compatible `styled-components` objects. 
They can also be defined as a function which can receive the button props, in case any extra logic is needed to determine styling.
> feat: Button variant styling proposal

- .storybook/config.js
- src/Form/Switch.js
- src/Form/Switch.stories.js
Realized this needed a little tweaking as well.
- Removes extra "padding"
- Adds flair to the transition
|Before|After|
|-|-|
| ![old-switch](https://user-images.githubusercontent.com/10860014/64391595-ed3f9f00-d00e-11e9-9dc6-fb27f27e40a6.gif) | ![new-switch](https://user-images.githubusercontent.com/10860014/64406698-13cdfc00-d048-11e9-9599-d22a8614fbcb.gif) |
> feat(Switch): Style Updates

- src/Button/Button.js
- src/Button/Button.stories.js
Text on full width buttons was aligning to the left. I can't think of a time where this would be desirable. So, I justified the content to the center.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/10860014/64572843-97c90200-d32e-11e9-8c33-5bcecd334205.png)|![image](https://user-images.githubusercontent.com/10860014/64572818-854ec880-d32e-11e9-9269-84cd1c14d681.png)|
Added to Button story as well.
> fix(Button): Centers text within full-width button

- src/Form/Checkbox.js
- src/Form/Checkbox.stories.js
When we have long labels, or when they wrap on mobile, the checkbox icon would become vertically centered, which looks weird.
> fix(Checkbox):  Support for long labels

- src/Flex/Flex.js
Was having an issue where if the component had a `ref` passed to it, it would be ignored since it was a functional component.
This will pass ref through.
> fix(Flex): Forwards ref to children

- src/Form/FormError.js
- src/Form/Input.js
- src/Form/Input.stories.js
- src/Form/Label.js
- src/Form/__snapshots__/DateInput.spec.js.snap
- src/Form/__snapshots__/PhoneInput.spec.js.snap
- src/theme.js
- Proper padding
- Default Icon color
- Default right Icon size
- Floating animation/styles
- New `isFloating` rule
- Textarea floating
- Form Error margin
- Form Error in story
> fix(Input): Padding, Icon color, & Floating changes

- package-lock.json
- package.json
- rollup.config.js
- src/Alert/Alert.js
- src/Badge/Badge.js
- src/Box/Box.js
- src/Button/Button.js
- src/Dropdown/Dropdown.stories.js
- src/Flex/Flex.js
- src/Grid/Column.js
- src/Grid/Container.js
- src/Grid/Row.js
- src/Modal/Modal.dropdownExample.js
- src/Modal/Modal.example.js
- src/Text/Text.js
- src/Text/Text.spec.js
- src/Text/Text.stories.js
- src/Text/__snapshots__/Text.spec.js.snap
- src/Text/index.js
- src/index.js
- src/theme.js
- `<Text as="h1" fontSize={100} color="primaryLight" />`
- Should allow us to remove many of our one-off styled components, which are typically used only to style some text
- Better performance for foundational components like Box and Flex with `compose`
- Better support for responsive styles, e.g. `<Box m={{ _: 0, sm: 12 }} />`, which says for all screens, apply 0 margin, and for small screens and up, apply a 12px margin
- Better organization
- Remove grid nesting
- Add 24px to space scale
- Allow breakpoints to be overridden
- Remove `order` style so styled-system can apply `order` responsively, e.g. `<Column order={{ _: -1, sm: 1 }} />`
- Prettier wasn't liking some of the implicit ternary returns
- Storybook was not liking hooks in the base story
- Modal was using old Dropdown syntax
> feat(Text): New Text component; upgrade to styled-system@v5

- src/Modal/Modal.js
This was introduced by `react-focus-on` & it's predecessor `react-focus-lock`. It wasn't necessarily a bug since it was doing what it was intended to do, and that is to make the modal accessible. In doing so, you lock the focus into the modal, and the first item it would focus on is an input or button. This would cause the modal to open near the bottom of the scroll length. I needed to make the header accessible as well since you could not navigate to the close button via the keyboard alone.
- Adds aria roles and tabIndex to Modal Header and buttons.
> fix(Modal): Opens long-content modal at top

- package-lock.json
`es-abstract@1.14.0` was unpublished which causes `npm install` to crash since it is in the lockfile. 🤦‍♀ 
Thanks to @schlegz for manually bumping packages to compare a working `package-lock.json` to the current  one. I have many questions and suggestions for alternative npm behavior but nevertheless install now works on a clean repo with latest `npm`.
> fix: bump es-abstract to fix npm install crash due to unpublished version

- src/theme.js
Secondary button variants should not have white background by default. Doing a final pass on web's design audit and the new secondary button in GoodRx header is incorrect.
> fix(Button): Remove backgroundColor from secondary variant

- src/Button/Button.js
- src/Form/Checkbox.js
- src/Form/Checkbox.stories.js
- src/Form/RadioGroup.js
- src/Form/RadioGroup.stories.js
- src/Form/Switch.js
- src/theme.js
Now when tabbing onto checkbox/radio, you can press space, or any other accessible key combo to check/uncheck the box.
Features:
- Adds a focus state to Switch, Button, Radio, and Checkboxes.
Breaking Changes:
- Checkbox and Radio are no longer 100% icons. They both use CSS to shape them. The only icon that is customizable is the checkbox check.
|Before|After|
|-|-|
|![Kapture 2019-12-04 at 16 33 17](https://user-images.githubusercontent.com/10860014/70187442-d105d980-16b3-11ea-9897-f3f2a910c631.gif)|![Kapture 2019-12-23 at 11 13 04](https://user-images.githubusercontent.com/10860014/71371006-4e1ac500-2575-11ea-84c8-52e8aa488bd7.gif)|
https://app.asana.com/0/1127722639002160/1148828435323497
> feat(Accessibility): Makes checkbox/radio accessible. Focus States updated.

- src/Button/Button.js
Semantically, `div` should not be inside a button component. This removes the div and styles the button accordingly.
Source: https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element
> fix(Button): Removes div from inside button

- src/Modal/Modal.js
This is specific to accessibility and testing in general (though it's not a change to make testing work right, this was a problem that was unearthed by testing actually).
Modals and their content were being rendered when not visible, and so readable by screen readers which would not make sense if it's not showing. Now, the modal and it's content will render when it is supposed to be visible. 🎉 
Makes the close icon a button. Also, it gives autofocus back to content.
No breaking changes.
> feat(Modal): Only renders modal in DOM when visible

- src/Modal/Modal.js
https://sentry.io/organizations/heydoctor/issues/1393699250/?referrer=slack
The modal backdrop would sometimes render after `onEntering` was called, so I wrapped in a conditional to prevent it from calling `.scroll` on the null object.
> fix(Modal): Safeguards against onEntering error

- src/Form/Label.js
Fixed the hidden label issue by forcing the label to have a higher z-index than the input.
https://app.asana.com/0/1127722639002160/1156115008597897/f
Make sure to allow Firefox to save the login credentials on the sign-in page. Log out, then go back to sign-in page.  Should look similar to screenshot above.
🛑  Does this affect patients?
✅ Does this affect clinical?
✅ Does this mutate data?
✅ Does it touch PHI?
✅ Does it touch payments?
> fix: set higher z-index for input labels

- package.json
Running `yarn release` then publishing would not package up new code in the uploaded tarball
> chore: Add build step to release script [skip ci]

- src/Form/Checkbox.js
- src/Form/Checkbox.stories.js
- src/Form/CheckboxGroup.js
- src/Form/GroupContainer.js
- src/Form/RadioGroup.js
- src/Form/RadioGroup.stories.js
- src/theme.js
Coming from feedback in https://github.com/heydoctor/web-app/pull/408
This will solve the regressions from that update while still keeping the features requested.
> fix(Checkbox/Radio): Fixes regression from 5.1.1 update

- src/Button/Button.js
Tired of seeing this console error
> fix(Button): Rename internal loading prop to isLoading to remove console error

- src/Modal/Modal.js
Moving the <ModalContent> out of <Backdrop> fixes this issue. I've checked that the transition animation used in <ModalContent> also applies opacity, so we don't need to reapply it despite <ModalContent> no longer being a child of <Backdrop>
This solution might also be advantageous should we later add a boolean prop to hide the backdrop. 
I also noticed that we're hardcoding z-index values, perhaps we could use library wide enum/const for z-indeces, so we can better track our z-index layering, should I create a story for this?
> fix: Move <ModalContent> out of <Backdrop> to prevent unwanted backdrop close

- src/Modal/Modal.js
https://app.asana.com/0/1172482803331797/1174613694180881
Part of the fix is to prevent the issue below. But this issue shouldn't really happen anymore because we're now making the ModalContent automatically scroll when necessary.
> fix: Prevent backdrop from scrolling away

- src/Modal/Modal.js
Asana Task:
https://app.asana.com/0/1172458003196612/1175644854344246
Apologies, I used height instead of max-height :/ 
Current Behavior:
Fixed Behavior:
Retains Original Intent:
> fix: use max-height for <ModalBody>

- package.json
📃 Summary
Setup Chromatic
Currently our GitHub checks break because chromatic exits non-zero on
changes, this means that since the changes haven't been reviewed on
chromatic, it breaks the CI and fails the rest of the checks. We don't
want this, we want the checks to continue properly, and master should be
auto-accepted as that's what the PR process is for.
Add two flags to chromatic yarn script to avoid breaking github checks
and auto-accept changes that make it to master.
🏷 Asana Task
https://app.asana.com/0/1127722595295875/1176049763317385
📸 Screenshots
🧪 QA
📈 Risk Analysis
✅ Does this affect patients?
✅ Does this affect clinical?
✅ Does this mutate data?
✅ Does it touch PHI?
✅ Does it touch payments?
✅ Does it update Node packages?
> chore: prevent chromatic from breaking ci

- src/theme.js
Updates button padding and the `sm` variant font-size to match our Figma design system. This was a request from Jay when we were doing a live QA bug bash. 
**Before**
**After**
> fix: Fix button padding and font sizes

- src/Modal/Modal.js
Fixes the position of the modal close icon so that it's flush with the edge of the container. 
| Before  | After |
| ------------- | ------------- |
| <img width="353" alt="Screen Shot 2020-05-26 at 10 34 13 AM" src="https://user-images.githubusercontent.com/6404663/82932304-0e4d7480-9f3d-11ea-97d4-a981abf11218.png">  | <img width="354" alt="Screen Shot 2020-05-26 at 10 33 35 AM" src="https://user-images.githubusercontent.com/6404663/82932314-11486500-9f3d-11ea-9b8b-24861067265b.png">  |
> fix: Adjust close icon position

- .github/workflows/ci.yml
- README.md
Adds github workflow tasks that automatically builds and publishes our
npm package. It will also build a canary version for development builds.
- Update ci.yml file with new tasks
- Update readme to reflect new auto-release
https://app.asana.com/0/0/1175870752691688/f
> chore: add auto publising master
